name: base
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
- cudatoolkit=10.1
- cudnn
- nccl
- python=3.6
- numpy
- pip
- pandas
- matplotlib
- seaborn
- tensorflow-gpu
- xgboost
- jupyter
- jupyterhub
